shutdown = 8000

[cgi]
api_cgi = { binary = "./api_cgi.py" }
cgi_tester = { binary = "./dl/cgi_tester" }

[server.maix]
host = "local.maix.me"
bind = "0.0.0.0"
port = 8088
root = "./static/"

[server.maix.routes."/"]
allowed = ["GET"]
index = "index.html"

[server.maix.routes."/api/"]
allowed = ["DELETE", "POST", "GET"]
cgi = { "api" = "api_cgi" }
root = "/var/empty"

[server.example]
host = "tester.local.maix.me"
bind = "0.0.0.0"
port = 8081
root = "./YoupiBanane/"

[server.example.routes."/"]
allowed = ["GET"]
cgi = { "bla" = "cgi_tester" }

[server.example.routes."/put_test/"]
allowed = ["PUT"]
cgi = { "bla" = "cgi_tester" }
post_directory = "./put_dir"

[server.example.routes."/post_body"]
allowed = ["POST"]
cgi = { "bla" = "cgi_tester" }
max_size = 100
post_directory = "./post_dir"

[server.example.routes."/directory/"]
allowed = ["GET", "POST"]
cgi = { "bla" = "cgi_tester" }
index = "youpi.bad_extension"
post_directory = "./post_dir"
max_size = 100000000
