shutdown = false

[cgi]
#cgi_tester = { binary = "./dl/cgi_tester" }
cgi_tester = { binary = "./dumper_cgi" }
#php_cgi = { binary = "php_cgi", from_env = false }
#env_php_cgi = { binary = "PHP_CGI", from_env = true }

[server.example]
host = "localhost"
bind = "0.0.0.0"
port = 0
root = "./YoupiBanane/"

[server.example.routes."/"]
allowed = ["GET"]
cgi = { "bla" = "cgi_tester" }

[server.example.routes."/put_test/"]
allowed = ["PUT"]
cgi = { "bla" = "cgi_tester" }
post_directory = "./put_dir"

[server.example.routes."/post_body"]
allowed = ["POST"]
cgi = { "bla" = "cgi_tester" }
max_size = 100
post_directory = "./post_dir"


[server.example.routes."/directory/"]
allowed = ["GET", "POST"]
cgi = { "bla" = "cgi_tester" }
index = "youpi.bad_extension"
post_directory = "./post_dir"
max_size = 100000000

#cgi = { php = "php_cgi1" }
