[cgi]
php_cgi = { binary = "php_cgi", from_env = false }
env_php_cgi = { binary = "PHP_CGI", from_env = true }

[server.example]
host = "local.maix.me"
bind = "0.0.0.0"
port = 1
errors = { 404 = "404.html" }
root = "/var/empty"

[server.example2]
host = "local.maix.me"
bind = "local.maix.me"
port = 1
errors = { 404 = "404.html" }
root = "/var/empty"


[server.example.routes."/"]
allowed = ["GET", "POST", "OPTION", "HEAD"]
root = "./data/contents"
index = "index.html"
listing = false
max_size = 16_000_000
post_directory = "./data/uploads"
#cgi = { php = "php_cgi1" }
