shutdown = false

[cgi]
#php_cgi = { binary = "php_cgi", from_env = false }
#env_php_cgi = { binary = "PHP_CGI", from_env = true }

[server.example]
host = "www.example.com"
bind = "0.0.0.0"
port = 0
errors = { 404 = "404.html" }
root = "./src"

#[server.example2]
#host = "local.maix.me"
#bind = "0.0.0.0"
#port = 4444
#errors = { 404 = "404.html" }
#root = "/var/empty"

[server.example.routes."/"]
allowed = ["GET", "POST", "OPTION", "HEAD"]
root = "./src"
#index = "index.html"
listing = true
max_size = 16_000_000
post_directory = "./data/uploads"


[server.example.routes."/xX_des_grosses_boules_de_glace_Xx"]
allowed = ["GET", "POST", "OPTION", "HEAD"]
root = "./data/contents"
redirect = "https://google.com"
max_size = 16_000_000
post_directory = "./data/uploads"
#cgi = { php = "php_cgi1" }
