shutdown = 8000

[cgi]
api_cgi = { binary = "python3" }
tester_cgi = { binary = "./dl/cgi_tester" }
sh_cgi = { binary = "/bin/sh" }

[server.maix]
host = "local.maix.me"
bind = "0.0.0.0"
port = 8088
root = "./static/"
errors = { 404 = "errors/404.html", 500 = "errors/500.html" }

[server.maix.routes."/"]
allowed = ["GET"]
index = "index.html"

[server.maix.routes."/api/"]
allowed = ["DELETE", "POST", "GET"]
cgi = { "py" = "api_cgi", "sh" = "sh_cgi" }

[server.example]
host = "tester.local.maix.me"
bind = "0.0.0.0"
port = 8081
root = "./YoupiBanane/"

[server.example.routes."/"]
allowed = ["GET"]
cgi = { "bla" = "tester_cgi" }

[server.example.routes."/put_test/"]
allowed = ["PUT"]
cgi = { "bla" = "tester_cgi" }
post_directory = "./put_dir"

[server.example.routes."/post_body"]
allowed = ["POST"]
cgi = { "bla" = "tester_cgi" }
max_size = 100
post_directory = "./post_dir"

[server.example.routes."/directory/"]
allowed = ["GET", "POST"]
cgi = { "bla" = "tester_cgi" }
index = "youpi.bad_extension"
root = "./YoupiBanane/"
post_directory = "./post_dir"
max_size = 100000000
