SRC_FILES =                                                                   \
CgiInstance                                                                   \
State                                                                         \
callback/Connection                                                           \
callback/File                                                                 \
callback/Shutdown                                                             \
callback/Socket                                                               \
callback/_Callback                                                            \
config/Cgi                                                                    \
config/Config                                                                 \
config/Route                                                                  \
config/Server                                                                 \
config/_checkConfig                                                           \
config/errors                                                                 \
config/print                                                                  \
fs/Directory                                                                  \
fs/File                                                                       \
http/Request                                                                  \
http/Response                                                                 \
http/Routing                                                                  \
http/StatusCode                                                               \
lib/Time                                                                      \
net/Socket                                                                    \
runtime/Epoll                                                                 \
runtime/Logger                                                                \
runtime/main                                                                  \
runtime/shim                                                                  \
toml/Parser/Parser                                                            \
toml/Parser/error/ForbiddenError                                              \
toml/Parser/error/InternalError                                               \
toml/Parser/error/SyntaxError                                                 \
toml/Parser/parsing/Context                                                   \
toml/Parser/parsing/createTomlValueInTable                                    \
toml/Parser/parsing/eatToken                                                  \
toml/Parser/parsing/nextToken                                                 \
toml/Parser/parsing/normalizeBasicStr                                         \
toml/Parser/parsing/normalizeDecimalString                                    \
toml/Parser/parsing/normalizeKey                                              \
toml/Parser/parsing/parseArray                                                \
toml/Parser/parsing/parseKeyValue                                             \
toml/Parser/parsing/parseSelect                                               \
toml/Parser/parsing/parseString                                               \
toml/Parser/parsing/parseTable                                                \
toml/Parser/parsing/scanString                                                \
toml/Parser/parsing/setToken                                                  \
toml/Parser/parsing/tablePath                                                 \
toml/Value/Value                                                              \
toml/Value/print                                                              \

